car_rental/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from car_rental import views

app_name = 'car_rental'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='car_rental/login.html'), name='login'),
    path('signup/', views.signup, name='signup'),
    path('requests/', views.RentRequestRenterListView.as_view(), name='requests_renter'),
    path('requests/staff/', views.RentRequestStaffListView.as_view(), name='requests_staff'),
    path('requests/answer/', views.answer_requests_view, name='answer_requests'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/<int:pk>/', views.UserDetailView.as_view(), name='user_info'),
    path('profile/password/', views.change_password, name='change_password'),
    path('profile/credit/', views.ChangeCreditView.as_view(), name='change_credit'),
    path('profile/logout/', views.logout_view, name='logout'),
    path('cars/', views.CarListRenterView.as_view(), name='cars'),
    path('cars/staff/', views.CarListStaffView.as_view(), name='cars_staff'),
    path('cars/add/', views.AddCarView.as_view(), name='add_car'),
    path('cars/<int:pk>/', views.CarDetailView.as_view(), name='car'),
    path('cars/<int:pk>/rent/', views.rent_request_view, name='rent_request'),
    path('cars/<int:pk>/edit/', views.EditCarView.as_view(), name='edit_car'),
    path('cars/<int:pk>/delete/', views.DeleteCarView.as_view(), name='delete_car'),
    path('cars/<int:pk>/repair/', views.NeedRepairCarView.as_view(), name='needs_repair'),
    path('staff/', views.StaffListView.as_view(), name='staff'),
    path('staff/add/', views.StaffCreateView.as_view(), name='add_staff'),
    path('staff/<int:pk>/', views.StaffDetailView.as_view(), name='staff_detail'),
    path('staff/<int:pk>/delete/', views.StaffDeleteView.as_view(), name='delete_staff'),
    path('staff/<int:pk>/perms/', views.ChangePermissions.as_view(), name='staff_perms')

]

car_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rental/', include('car_rental.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car_rental/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.utils import timezone

from car_rental.models import User, Staff


class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = cleaned_data['username']
        password = cleaned_data['password']

        if username and password:
            user = authenticate(username=username, password=password)
            if (user is None) or (not user.is_active):
                raise ValidationError("Username and Password didn't match.")
        return cleaned_data


class ChangeCreditForm(forms.Form):
    delta_credit = forms.IntegerField(label='Delta Credit')


class SignUpForm(UserCreationForm):
    CHOICES = [('EX', 'Exhibition'),
               ('R', 'Renter')]

    user_type = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect, label='Who are you?')

    class Meta:
        model = User
        fields = ('username', 'user_type', 'password1', 'password2',)


class StaffCreationForm(UserCreationForm):
    CHOICES = [('N', 'Normal'),
               ('S', 'Senior')]

    staff_type = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect,
                                   label='What kind of staff are you adding?')

    class Meta:
        model = User
        fields = ('username', 'staff_type', 'password1', 'password2',)


class RentRequestForm(forms.Form):
    rent_start_time = forms.DateTimeField()
    rent_end_time = forms.DateTimeField()

    def clean(self):
        cleaned_data = super(RentRequestForm, self).clean()
        rent_start_time = cleaned_data['rent_start_time']
        rent_end_time = cleaned_data['rent_end_time']

        if rent_end_time and rent_end_time:
            if rent_end_time <= rent_start_time or rent_start_time < timezone.now():
                raise ValidationError("Request is not valid.")
        return cleaned_data


class StaffPermissionsForm(forms.ModelForm):
    PERMISSION_CHOICES = [('CREDIT', 'credit access'), ('REQUEST', 'request access'),
                          ('CAR', 'car access'), ('STAFF', 'access staff')]
    perms = forms.MultipleChoiceField(choices=PERMISSION_CHOICES, widget=forms.CheckboxSelectMultiple,
                                      label='What permissions should this user have?', required=False)

    def __init__(self, *args, **kwargs):
        super(StaffPermissionsForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Staff
        fields = []

car_rental/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, update_session_auth_hash, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import Permission
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import generic
from django_filters import views as filter_views
from django_tables2.views import SingleTableMixin

from . import decorators
from . import filters as my_filters
from .forms import StaffCreationForm
from .models import Car, RentRequest, User, Exhibition, Staff
from . import forms as my_forms
from . import tables as my_tables


@method_decorator(decorators.user_is_not_staff, name='dispatch')
class CarListRenterView(filter_views.FilterView):
    template_name = 'car_rental/car_list.html'
    model = Car
    context_object_name = 'cars'
    filterset_class = my_filters.CarFilterSet

    def get_queryset(self):
        return Car.objects.exclude(rent_end_time__gt=timezone.now()).filter(needs_repair=False)


@method_decorator(decorators.user_is_staff, name='dispatch')
class CarListStaffView(SingleTableMixin, filter_views.FilterView):
    template_name = 'car_rental/car_list_staff.html'
    model = Car
    context_object_name = 'cars'
    paginate_by = 7
    filterset_class = my_filters.CarFilterSet
    table_class = my_tables.CarStaffTable

    def get_queryset(self):
        current_user = self.request.user
        return current_user.staff.exhibition.cars_owned.all()


class CarDetailView(generic.DetailView):
    model = Car
    context_object_name = 'car'
    template_name = 'car_rental/car_detail.html'

    def get_queryset(self):
        return Car.objects.all()


@login_required()
def rent_request_view(request, pk):
    car = get_object_or_404(Car, id=pk)
    if request.method == 'POST':
        form = my_forms.RentRequestForm(request.POST)
        if form.is_valid():
            rent_start_time = form.cleaned_data.get('rent_start_time')
            rent_end_time = form.cleaned_data.get('rent_end_time')
            rent_req = RentRequest.objects.create(car=car, requester=request.user, rent_end_time=rent_end_time,
                                                  rent_start_time=rent_start_time)
            rent_req.save()
            return HttpResponseRedirect(reverse('car_rental:requests_renter'))
    messages.error(request, 'Please enter valid start and end time.')
    return HttpResponseRedirect(reverse('car_rental:car', kwargs={'pk': pk}))


@method_decorator(login_required, name='dispatch')
@method_decorator(decorators.user_is_not_staff, name='dispatch')
class RentRequestRenterListView(SingleTableMixin, filter_views.FilterView):
    template_name = 'car_rental/request_list_renter.html'
    model = RentRequest
    context_object_name = 'requests'
    paginate_by = 7
    filterset_class = my_filters.RentRequestFilterSet
    table_class = my_tables.RentRequestRenterTable

    def get_queryset(self):
        current_user = self.request.user
        return current_user.rentrequest_set.all().order_by('-rent_start_time')


@method_decorator(login_required, name='dispatch')
@method_decorator(decorators.user_is_staff, name='dispatch')
class RentRequestStaffListView(PermissionRequiredMixin, generic.ListView):
    template_name = 'car_rental/request_list_staff.html'
    model = RentRequest
    context_object_name = 'requests'
    permission_required = 'car_rental.can_answer_request'

    def get_queryset(self):
        current_user = self.request.user
        return current_user.staff.exhibition.get_all_requests().order_by('rent_start_time').filter(has_result=False)


@login_required()
@decorators.user_is_staff
@permission_required('car_rental.can_answer_request', raise_exception=True)
def answer_requests_view(request):
    user = request.user
    if request.method == 'POST':
        unanswered_requests = user.staff.exhibition.get_all_requests().filter(has_result=False)
        for unanswered_request in unanswered_requests:
            try:
                answer = request.POST[str(unanswered_request.id)]
                if answer == 'yes':
                    if unanswered_request.car.is_rented():
                        messages.error(request,
                                       'Car ' + unanswered_request.car.car_type + ' is already rented.')
                        unanswered_request.reject(user)
                    else:
                        unanswered_request.accept(user)
                elif answer == 'no':
                    unanswered_request.reject(user)
                else:
                    pass
            except KeyError:
                pass
    return HttpResponseRedirect(reverse('car_rental:requests_staff'))


@login_required()
def profile_view(request):
    return render(request, 'car_rental/profile.html')


@login_required()
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('car_rental:profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'car_rental/change_password.html', {'form': form})


@method_decorator(login_required, name='dispatch')
class ChangeCreditView(PermissionRequiredMixin, generic.FormView):
    template_name = 'car_rental/change_credit.html'
    form_class = my_forms.ChangeCreditForm
    permission_required = 'car_rental.can_access_credit'

    def form_valid(self, form):
        delta_credit = form.cleaned_data['delta_credit']
        current_user = self.request.user
        current_user.change_credit(delta_credit)
        return HttpResponseRedirect(reverse('car_rental:profile'))


def home_view(request):
    return render(request, 'car_rental/home.html')


@login_required()
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('car_rental:home'))


def create_exhibition(user):
    exhibition = Exhibition.objects.create(name=user.username)
    exhibition.save()
    senior_staff = Staff.objects.create(exhibition=exhibition, is_senior=True, user=user)
    senior_staff.save()


def signup(request):
    if request.method == 'POST':
        form = my_forms.SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user_type = form.cleaned_data.get('user_type')
            user = authenticate(username=username, password=raw_password)
            if user_type == 'EX':
                create_exhibition(user)
            else:
                user.user_permissions.add(Permission.objects.get(codename='can_access_credit'))
            login(request, user)
            return HttpResponseRedirect(reverse('car_rental:home'))
    else:
        form = my_forms.SignUpForm()
    return render(request, 'car_rental/signup.html', {'form': form})


@method_decorator(login_required, name='dispatch')
@method_decorator(decorators.user_is_staff, name='dispatch')
class AddCarView(PermissionRequiredMixin, generic.CreateView):
    model = Car
    template_name = 'car_rental/add_car.html'
    fields = ['car_type', 'plate', 'price_per_hour', 'image']
    permission_required = 'car_rental.can_access_car'

    def form_valid(self, form):
        response = super(AddCarView, self).form_valid(form)
        current_user = User.objects.get(id=self.request.user.id)
        self.object.set_owner(current_user.staff.exhibition)
        return response


@method_decorator(login_required, name='dispatch')
@method_decorator(decorators.user_is_staff, name='dispatch')
class EditCarView(PermissionRequiredMixin, generic.UpdateView):
    model = Car
    template_name = 'car_rental/edit_car.html'
    fields = ['price_per_hour']
    permission_required = 'car_rental.can_access_car'

    def get_queryset(self):
        current_user = self.request.user
        return current_user.staff.exhibition.cars_owned.filter(rent_end_time__lte=timezone.now())


@method_decorator(login_required, name='dispatch')
class DeleteCarView(PermissionRequiredMixin, generic.DeleteView):
    model = Car
    template_name = 'car_rental/delete_car.html'
    permission_required = 'car_rental.can_access_car'

    def get_success_url(self):
        return reverse('car_rental:cars')

    def get_queryset(self):
        current_user = self.request.user
        return current_user.staff.exhibition.cars_owned.filter(rent_end_time__lte=timezone.now())


@method_decorator(login_required, name='dispatch')
class UserDetailView(PermissionRequiredMixin, generic.DetailView):
    model = User
    context_object_name = 'user'
    template_name = 'car_rental/user_info.html'
    permission_required = 'car_rental.can_answer_request'

    def get_queryset(self):
        current_user = self.request.user
        queryset = User.objects.none()
        if current_user.is_staff:
            for rent_request in current_user.staff.exhibition.get_all_requests():
                queryset |= User.objects.filter(id=rent_request.requester.id)
        return queryset


@method_decorator(login_required, name='dispatch')
class NeedRepairCarView(generic.UpdateView):
    model = Car
    template_name = 'car_rental/need_repair.html'
    fields = ['needs_repair']

    def form_valid(self, form):
        response = super(NeedRepairCarView, self).form_valid(form)

car_rental/templates/car_rental/includes/messages.html
<ul class="messages container" style="list-style-type: none">
    {% for message in messages %}
    <li     style="margin-bottom: 5px; margin-top: 5px" role="alert"
            {% if message.tags %} class="{{ message.tags }} alert alert-dismissible fade show"{% endif %}>
        {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
    </li>
    {% endfor %}
</ul>

car_rental/templates/car_rental/includes/navbar.html
<nav class="navbar navbar-dark navbar-expand-md">
    <span class="navbar-brand mb-0 h1">Car Rental</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarItems"
            area-controls="navbarItems" aria-expanded="false" area-lable="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarItems">
        <ul class="navbar-nav">
{% with url_name=request.resolver_match.url_name %}
            <li class="nav-item {% if url_name == 'home' %}active{% endif %}">
                <a class="nav-link" href="{% url 'car_rental:home' %}">Home</a>
            </li>
    {% if user.is_staff %}
            <li class="nav-item {% if url_name == 'cars_staff' %}active{% endif %}">
                <a class="nav-link" href="{% url 'car_rental:cars_staff' %}">Cars</a>
            </li>
    {% else %}
            <li class="nav-item {% if url_name == 'cars' %}active{% endif %}">
                <a class="nav-link" href="{% url 'car_rental:cars' %}">Cars</a>
            </li>
    {% endif %}

{% if not user.is_anonymous %}
            <li class="nav-item {% if url_name == 'profile' %}active{% endif %}">
                <a class="nav-link" href="{% url 'car_rental:profile' %}">Profile</a>
            </li>

    {% if user.is_staff %}
        {% if perms.car_rental.can_answer_request %}
            <li class="nav-item {% if url_name == 'requests_staff' %}active{% endif %}">
                <a class="nav-link" href="{% url 'car_rental:requests_staff' %}">Requests</a>
            </li>
        {% endif %}
    {% else %}
            <li class="nav-item {% if url_name == 'requests_renter' %}active{% endif %}">
                <a class="nav-link" href="{% url 'car_rental:requests_renter' %}">Requests</a>
            </li>
    {% endif %}
        {% if perms.car_rental.can_access_staff %}
        <li class="nav-item {% if url_name == 'staff'%}active{% endif %}">
            <a class="nav-link" href="{% url 'car_rental:staff' %}">Staff</a>
        </li>
        <li class="nav-item {% if url_name == 'add_staff'%}active{% endif %}">
            <a class="nav-link" href="{% url 'car_rental:add_staff' %}">Add Staff</a>
        </li>
        {% endif %}
        {% if perms.car_rental.can_access_car %}
        <li class="nav-item {% if url_name == 'add_car' %}active{% endif %}">
                <a class="nav-link" href="{% url 'car_rental:add_car' %}">Add Car</a>
        </li>
    {% endif %}
{% endif %}
    </ul>
    <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if url_name == 'login' %}active{% endif %}">
                <a class="nav-link" href="{% url 'car_rental:login' %}">Login</a>
            </li>

            <li class="nav-item {% if url_name == 'signup' %}active{% endif %}">
                <a class="nav-link" href="{% url 'car_rental:signup' %}">Sign up</a>
            </li>
    {% if not user.is_anonymous %}
            <li class="nav-item">
                <a class="nav-link btn btn-info" style="color: white;font-size: 18px;" href="{% url 'car_rental:logout' %}">Logout</a>
            </li>
    {% endif %}
    </ul>
    {% endwith %}
    </div>
</nav>