car_rental/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from car_rental import views

app_name = 'car_rental'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='car_rental/login.html'), name='login'),
    path('signup/', views.signup, name='signup'),
    path('requests/', views.RentRequestRenterListView.as_view(), name='requests_renter'),
    path('requests/staff/', views.RentRequestStaffListView.as_view(), name='requests_staff'),
    path('requests/answer/', views.answer_requests_view, name='answer_requests'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/<int:pk>/', views.UserDetailView.as_view(), name='user_info'),
    path('profile/password/', views.change_password, name='change_password'),
    path('profile/credit/', views.ChangeCreditView.as_view(), name='change_credit'),
    path('profile/logout/', views.logout_view, name='logout'),
    path('cars/', views.CarListRenterView.as_view(), name='cars'),
    path('cars/staff/', views.CarListStaffView.as_view(), name='cars_staff'),
    path('cars/add/', views.AddCarView.as_view(), name='add_car'),
    path('cars/<int:pk>/', views.CarDetailView.as_view(), name='car'),
    path('cars/<int:pk>/rent/', views.rent_request_view, name='rent_request'),
    path('cars/<int:pk>/edit/', views.EditCarView.as_view(), name='edit_car'),
    path('cars/<int:pk>/delete/', views.DeleteCarView.as_view(), name='delete_car'),
    path('cars/<int:pk>/repair/', views.NeedRepairCarView.as_view(), name='needs_repair'),
    path('staff/', views.StaffListView.as_view(), name='staff'),
    path('staff/add/', views.StaffCreateView.as_view(), name='add_staff'),
    path('staff/<int:pk>/', views.StaffDetailView.as_view(), name='staff_detail'),
    path('staff/<int:pk>/delete/', views.StaffDeleteView.as_view(), name='delete_staff'),
    path('staff/<int:pk>/perms/', views.ChangePermissions.as_view(), name='staff_perms')

]

car_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rental/', include('car_rental.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car_rental/models.py
import datetime
from math import ceil

from django.contrib.auth.models import AbstractUser, Permission
from django.db import models
from django.urls import reverse
from django.utils import timezone


def get_tomorrow():
    return timezone.now() + datetime.timedelta(days=1)


class User(AbstractUser):
    credit = models.IntegerField(default=0)

    def change_credit(self, delta_credit):
        if self.is_staff:
            self.staff.exhibition.change_credit(delta_credit)
        else:
            self.credit += delta_credit
            self.save()

    def __str__(self):
        return self.username + " :  " + ('Car Exhibition' if self.is_staff else 'Renter')


class Exhibition(models.Model):
    name = models.CharField(max_length=200)
    credit = models.IntegerField(default=0)

    class Meta:
        permissions = (('can_access_credit', 'Can access credit'),)

    def get_all_requests(self):
        return RentRequest.objects.filter(car__owner=self)

    def change_credit(self, delta_credit):
        self.credit += delta_credit
        self.save()


class StaffManager(models.Manager):

    def create(self, *args, **kwargs):
        staff = super(StaffManager, self).create(*args, **kwargs)
        user = staff.user
        user.is_staff = True
        user.save()
        if staff.is_senior:
            staff.add_permissions('can_access_credit', 'can_answer_request', 'can_access_car', 'can_access_staff')
        else:
            staff.remove_permissions('can_access_credit')
        return staff


class Staff(models.Model):
    is_senior = models.BooleanField(default=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    exhibition = models.ForeignKey(Exhibition, on_delete=models.CASCADE)
    objects = StaffManager()

    class Meta:
        permissions = (('can_access_staff', 'Can access staff'),)

    def add_permissions(self, *codenames):
        for codename in codenames:
            permission = Permission.objects.get(codename=codename)
            self.user.user_permissions.add(permission)

    def remove_permissions(self, *codenames):
        for codename in codenames:
            permission = Permission.objects.get(codename=codename)
            self.user.user_permissions.remove(permission)

    def get_absolute_url(self):
        return reverse('car_rental:staff_detail', kwargs={'pk': self.id})


class Car(models.Model):
    car_type = models.CharField(max_length=50, default='type0')
    plate = models.CharField(max_length=8, default='12345678')
    renter = models.ForeignKey(User, null=True, default=None, on_delete=models.SET_NULL, related_name='cars_rented')
    owner = models.ForeignKey(Exhibition, on_delete=models.CASCADE, null=True, related_name='cars_owned')
    price_per_hour = models.IntegerField(default=10)
    rent_start_time = models.DateTimeField('Start Time', default=timezone.now)
    rent_end_time = models.DateTimeField('End Time', default=timezone.now)
    needs_repair = models.BooleanField(default=False)
    image = models.ImageField(upload_to='cars', null=True, blank=True, default='default.jpg')

    class Meta:
        permissions = (('can_access_car', 'Can access car'),)

    def __str__(self):
        return str(self.pk) + ". " + self.car_type

    def is_rented(self):
        return self.rent_end_time > timezone.now()

    def set_renter(self, renter):
        self.renter = renter
        self.save()

    def set_owner(self, owner):
        self.owner = owner
        self.save()

    def get_absolute_url(self):
        return reverse('car_rental:car', kwargs={'pk': self.id})


class RentRequest(models.Model):
    price = models.IntegerField(default=0)
    is_accepted = models.BooleanField(default=False)
    has_result = models.BooleanField(default=False)
    car = models.ForeignKey(Car, on_delete=models.SET_NULL, null=True)
    requester = models.ForeignKey(User, on_delete=models.CASCADE)
    rent_start_time = models.DateTimeField('Start Time', default=timezone.now)
    rent_end_time = models.DateTimeField('End Time', default=get_tomorrow)
    creation_time = models.DateTimeField('Request time:', default=timezone.now)
    responser = models.ForeignKey(Staff, on_delete=models.SET_NULL, default=None, null=True)

    class Meta:
        permissions = (('can_answer_request', 'Can answer requests'),)

    def accept(self, user):
        self.is_accepted = True
        self.has_result = True
        self.responser = user.staff
        self.price = self.get_price()
        self.save()
        car = self.car
        car.renter = self.requester
        car.rent_end_time = self.rent_end_time
        car.rent_start_time = self.rent_start_time
        car.save()
        self.requester.change_credit(-self.price)
        car.owner.change_credit(self.price)

    def reject(self, user):
        self.is_accepted = False
        self.has_result = True
        self.responser = user.staff
        self.price = self.get_price()
        self.save()

    def get_price(self):
        if self.price == 0:
            delta_time = self.rent_end_time - self.rent_start_time
            delta_hours = delta_time.days * 24 + ceil(delta_time.seconds/3600)
            return delta_hours * self.car.price_per_hour
        else:
            return self.price

car_rental/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, update_session_auth_hash, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import Permission
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import generic
from django_filters import views as filter_views
from django_tables2.views import SingleTableMixin

from . import decorators
from . import filters as my_filters
from .forms import StaffCreationForm
from .models import Car, RentRequest, User, Exhibition, Staff
from . import forms as my_forms
from . import tables as my_tables


@method_decorator(decorators.user_is_not_staff, name='dispatch')
class CarListRenterView(filter_views.FilterView):
    template_name = 'car_rental/car_list.html'
    model = Car
    context_object_name = 'cars'
    filterset_class = my_filters.CarFilterSet

    def get_queryset(self):
        return Car.objects.exclude(rent_end_time__gt=timezone.now()).filter(needs_repair=False)


@method_decorator(decorators.user_is_staff, name='dispatch')
class CarListStaffView(SingleTableMixin, filter_views.FilterView):
    template_name = 'car_rental/car_list_staff.html'
    model = Car
    context_object_name = 'cars'
    paginate_by = 7
    filterset_class = my_filters.CarFilterSet
    table_class = my_tables.CarStaffTable

    def get_queryset(self):
        current_user = self.request.user
        return current_user.staff.exhibition.cars_owned.all()


class CarDetailView(generic.DetailView):
    model = Car
    context_object_name = 'car'
    template_name = 'car_rental/car_detail.html'

    def get_queryset(self):
        return Car.objects.all()


@login_required()
def rent_request_view(request, pk):
    car = get_object_or_404(Car, id=pk)
    if request.method == 'POST':
        form = my_forms.RentRequestForm(request.POST)
        if form.is_valid():
            rent_start_time = form.cleaned_data.get('rent_start_time')
            rent_end_time = form.cleaned_data.get('rent_end_time')
            rent_req = RentRequest.objects.create(car=car, requester=request.user, rent_end_time=rent_end_time,
                                                  rent_start_time=rent_start_time)
            rent_req.save()
            return HttpResponseRedirect(reverse('car_rental:requests_renter'))
    messages.error(request, 'Please enter valid start and end time.')
    return HttpResponseRedirect(reverse('car_rental:car', kwargs={'pk': pk}))


@method_decorator(login_required, name='dispatch')
@method_decorator(decorators.user_is_not_staff, name='dispatch')
class RentRequestRenterListView(SingleTableMixin, filter_views.FilterView):
    template_name = 'car_rental/request_list_renter.html'
    model = RentRequest
    context_object_name = 'requests'
    paginate_by = 7
    filterset_class = my_filters.RentRequestFilterSet
    table_class = my_tables.RentRequestRenterTable

    def get_queryset(self):
        current_user = self.request.user
        return current_user.rentrequest_set.all().order_by('-rent_start_time')


@method_decorator(login_required, name='dispatch')
@method_decorator(decorators.user_is_staff, name='dispatch')
class RentRequestStaffListView(PermissionRequiredMixin, generic.ListView):
    template_name = 'car_rental/request_list_staff.html'
    model = RentRequest
    context_object_name = 'requests'
    permission_required = 'car_rental.can_answer_request'

    def get_queryset(self):
        current_user = self.request.user
        return current_user.staff.exhibition.get_all_requests().order_by('rent_start_time').filter(has_result=False)


@login_required()
@decorators.user_is_staff
@permission_required('car_rental.can_answer_request', raise_exception=True)
def answer_requests_view(request):
    user = request.user
    if request.method == 'POST':
        unanswered_requests = user.staff.exhibition.get_all_requests().filter(has_result=False)
        for unanswered_request in unanswered_requests:
            try:
                answer = request.POST[str(unanswered_request.id)]
                if answer == 'yes':
                    if unanswered_request.car.is_rented():
                        messages.error(request,
                                       'Car ' + unanswered_request.car.car_type + ' is already rented.')
                        unanswered_request.reject(user)
                    else:
                        unanswered_request.accept(user)
                elif answer == 'no':
                    unanswered_request.reject(user)
                else:
                    pass
            except KeyError:
                pass
    return HttpResponseRedirect(reverse('car_rental:requests_staff'))


@login_required()
def profile_view(request):
    return render(request, 'car_rental/profile.html')


@login_required()
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('car_rental:profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'car_rental/change_password.html', {'form': form})


@method_decorator(login_required, name='dispatch')
class ChangeCreditView(PermissionRequiredMixin, generic.FormView):
    template_name = 'car_rental/change_credit.html'
    form_class = my_forms.ChangeCreditForm
    permission_required = 'car_rental.can_access_credit'

    def form_valid(self, form):
        delta_credit = form.cleaned_data['delta_credit']
        current_user = self.request.user
        current_user.change_credit(delta_credit)
        return HttpResponseRedirect(reverse('car_rental:profile'))


def home_view(request):
    return render(request, 'car_rental/home.html')


@login_required()
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('car_rental:home'))


def create_exhibition(user):
    exhibition = Exhibition.objects.create(name=user.username)
    exhibition.save()
    senior_staff = Staff.objects.create(exhibition=exhibition, is_senior=True, user=user)
    senior_staff.save()


def signup(request):
    if request.method == 'POST':
        form = my_forms.SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user_type = form.cleaned_data.get('user_type')
            user = authenticate(username=username, password=raw_password)
            if user_type == 'EX':
                create_exhibition(user)
            else:
                user.user_permissions.add(Permission.objects.get(codename='can_access_credit'))
            login(request, user)
            return HttpResponseRedirect(reverse('car_rental:home'))
    else:
        form = my_forms.SignUpForm()
    return render(request, 'car_rental/signup.html', {'form': form})


@method_decorator(login_required, name='dispatch')
@method_decorator(decorators.user_is_staff, name='dispatch')
class AddCarView(PermissionRequiredMixin, generic.CreateView):
    model = Car
    template_name = 'car_rental/add_car.html'
    fields = ['car_type', 'plate', 'price_per_hour', 'image']
    permission_required = 'car_rental.can_access_car'

    def form_valid(self, form):
        response = super(AddCarView, self).form_valid(form)
        current_user = User.objects.get(id=self.request.user.id)
        self.object.set_owner(current_user.staff.exhibition)
        return response


@method_decorator(login_required, name='dispatch')
@method_decorator(decorators.user_is_staff, name='dispatch')
class EditCarView(PermissionRequiredMixin, generic.UpdateView):
    model = Car
    template_name = 'car_rental/edit_car.html'
    fields = ['price_per_hour']
    permission_required = 'car_rental.can_access_car'

    def get_queryset(self):
        current_user = self.request.user
        return current_user.staff.exhibition.cars_owned.filter(rent_end_time__lte=timezone.now())


@method_decorator(login_required, name='dispatch')
class DeleteCarView(PermissionRequiredMixin, generic.DeleteView):
    model = Car
    template_name = 'car_rental/delete_car.html'
    permission_required = 'car_rental.can_access_car'

    def get_success_url(self):
        return reverse('car_rental:cars')

    def get_queryset(self):
        current_user = self.request.user
        return current_user.staff.exhibition.cars_owned.filter(rent_end_time__lte=timezone.now())


@method_decorator(login_required, name='dispatch')
class UserDetailView(PermissionRequiredMixin, generic.DetailView):
    model = User
    context_object_name = 'user'
    template_name = 'car_rental/user_info.html'
    permission_required = 'car_rental.can_answer_request'

    def get_queryset(self):
        current_user = self.request.user
        queryset = User.objects.none()
        if current_user.is_staff:
            for rent_request in current_user.staff.exhibition.get_all_requests():
                queryset |= User.objects.filter(id=rent_request.requester.id)
        return queryset


@method_decorator(login_required, name='dispatch')
class NeedRepairCarView(generic.UpdateView):
    model = Car
    template_name = 'car_rental/need_repair.html'
    fields = ['needs_repair']

    def form_valid(self, form):
        response = super(NeedRepairCarView, self).form_valid(form)

car_rental/templates/car_rental/profile.html
{% extends 'car_rental/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block title %} Profile {% endblock %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'car_rental/stylesheets/car_detail.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'car_rental/stylesheets/request_list.css' %}">

{% endblock %}


{% block content %}
    <div class="container">
        <h1>Your Profile</h1>
        <table class="table table-striped table-hover info-table">
            <tr>
                <td>Username</td>
                <td>{{ user.username }}</td>
            </tr>

            <tr>
                <td>Type</td>
                <td>
                    {% if user.is_staff %}
                        Exhibition{% if user.staff.is_senior %} Senior{% endif %} Staff
                    {% else %} Renter {% endif %}
                </td>
            </tr>
            <tr>
                <td>User ID</td>
                <td>{{ user.id }}</td>
            </tr>
            {% if user.is_staff %}
                <tr>
                    <td>Exhibition</td>
                    <td>{{ user.staff.exhibition.name }}</td>
                </tr>
                <tr>
                    <td>Exhibition ID</td>
                    <td>{{ user.staff.exhibition.id }}</td>
                </tr>
            {% endif %}
            {% if not user.is_staff or perms.car_rental.can_access_credit %}
                <tr>
                    {% if user.is_staff %}
                        <td>Exhibition Credit</td>
                        <td>{{ user.staff.exhibition.credit }}</td>
                    {% else %}
                        <td>Credit</td>
                        <td>{{ user.credit }}</td>
                    {% endif %}
                </tr>
            {% endif %}

        </table>

        <a class="btn btn-info" href="{% url 'car_rental:change_password' %}" role="button" style="width:19%">Change Password</a> &nbsp;
        {% if  perms.car_rental.can_access_credit %}
            <a class="btn btn-info" href="{% url 'car_rental:change_credit' %}" role="button" style="width:19%">Change Credit</a>
        {% endif %}

        {% if success_message %}
            <div class="alert alert-success" style="margin-top: 20px">{{ success_message }}</div>
        {% endif %}



        {% if user.staff.rentrequest_set.all %}
            <h1>Answered Requests</h1>

            <table class="table table-striped table-hover" style="margin-top: 20px">
                <thead>
                <tr>
                    <td>#</td>
                    <td>Model</td>
                    <td>Start Time</td>
                    <td>End Time</td>
                    <td>Price</td>
                    <td>Result</td>
                </tr>
                </thead>
                <tbody>
                {% for request in user.staff.rentrequest_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            {% if request.car %}
                            <a href="{% url 'car_rental:car' request.car.id %}">{{ request.car.car_type }}</a>
                            {% else %}
                            Deleted Car
                            {% endif %}
                        </td>
                        <td>{{ request.rent_start_time }}</td>
                        <td>{{ request.rent_end_time }}</td>
                        <td>{{ request.get_price }}</td>
                        {% if request.is_accepted %}
                            <td style="color: darkgreen">Accepted</td>
                        {% else %}
                            <td style="color: darkred">Rejected</td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            {% if perms.car_rental.can_answer_request %}
            <div class="alert alert-danger" style="margin-top: 10px"><strong>You have answered no requests till now.</strong></div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

car_rental/templates/car_rental/request_list.html
{% extends 'car_rental/base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Your Requests{% endblock %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'car_rental/stylesheets/request_list.css' %}">
{% endblock%}

{% block content %}
<div class="container">

<h1>Your Requests</h1>
{% if error_message %}
    <div class="alert alert-danger" ><strong>{{ error_message}}</strong></div>
{% endif %}

{%if  user.is_staff %}
    {% if requests %}
        <div class="alert alert-info"> Please accept or reject these requests:</div>
        <form action="{% url 'car_rental:answer_requests' %}" method="post">
        {% csrf_token %}
        <table class="table  table-striped table-hover">
        <thead>
        <tr>
            <td>#</td>
            <td>Model</td>
            <td>Plate Number</td>
            <td>Requester</td>
            <td>Start Time</td>
            <td>End Time</td>
            <td>Income</td>
            <td>Take it?</td>
        </tr>
        </thead>
        <tbody>
        {% for request in requests %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'car_rental:car' request.car.id %}">
                        {{ request.car.car_type }}
                    </a>
                </td>
                <td>{{ request.car.plate }}</td>
                <td>
                    <a href="{% url 'car_rental:user_info' request.requester.id %}">
                        {{ request.requester.username }}
                    </a>
                </td>
                <td>{{ request.rent_start_time }}</td>
                <td>{{ request.rent_end_time }}</td>
                <td>{{ request.get_price }}</td>
                <td>
                    <label for="yes{{ forloop.counter }}">Yes</label>
                    <input type="radio" id="yes{{ forloop.counter }}" name="{{ request.id }}" value="yes">
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <label for="no{{ forloop.counter }}">No</label>
                    <input type="radio" id="no{{ forloop.counter }}" name="{{ request.id }}" value="no">
                </td>
            </tr>
         {% endfor %}
        </tbody>
        </table>
        <input value="Confirm" type="submit" class="btn btn-info">
        </form>
    {% else %}
        <div class="alert alert-danger"><strong>No Requests.</strong></div>
    {% endif %}
{% else %}
    {{ filter.form.media }}
    <form action="" method="get" style="margin-bottom: 10px" class="form-inline">
    {{ filter.form|crispy }}
        <input type="submit" value="search" class="btn btn-info"/>
    </form>
    {% if requests %}
        <table class="table table-striped table-hover">
        <thead>
        <tr>
            <td>#</td>
            <td>Model</td>
            <td>Owner</td>
            <td>Start Time</td>
            <td>End Time</td>
            <td>Price</td>
            <td>status</td>
        </tr>
        </thead>
        <tbody>
        {% for request in requests %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    {% if request.car %}
                    <a href="{% url 'car_rental:car' request.car.id %}">{{ request.car.car_type }}</a>
                    {% else %}
                    Deleted Car
                    {% endif %}
                </td>
                <td>{{ request.car.owner.name }}</td>
                <td>{{ request.rent_start_time }}</td>
                <td>{{ request.rent_end_time }}</td>
                <td>{{ request.get_price }}</td>
            {% if request.has_result %}
                {% if request.is_accepted %}
                    <td style="color: darkgreen">Accepted</td>
                {% else %}
                    <td style="color: darkred">Rejected</td>
                {% endif %}
            {% else %}
                <td>Not determined yet</td>
            {% endif %}
            </tr>
         {% endfor %}
        </tbody>
        </table>
    {% else %}
        <div class="alert alert-danger"><strong>No Requests.</strong></div>
    {% endif %}

{% endif %}
</div>
{% endblock %}

car_rental/templates/car_rental/request_list_staff.html
{% extends 'car_rental/base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Your Requests{% endblock %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'car_rental/stylesheets/request_list.css' %}">
{% endblock%}

{% block content %}
<div class="container">

<h1>Your Requests</h1>
    {% if requests %}
        <div class="alert alert-info"> Please accept or reject these requests:</div>
        <form action="{% url 'car_rental:answer_requests' %}" method="post">
        {% csrf_token %}
        <table class="table table-hover">
        <thead>
        <tr>
            <td>#</td>
            <td>Model</td>
            <td>Plate Number</td>
            <td>Requester</td>
            <td>Start Time</td>
            <td>End Time</td>
            <td>Income</td>
            <td>Take it?</td>
        </tr>
        </thead>
        <tbody>
        {% for request in requests %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'car_rental:car' request.car.id %}">
                        {{ request.car.car_type }}
                    </a>
                </td>
                <td>{{ request.car.plate }}</td>
                <td>
                    <a href="{% url 'car_rental:user_info' request.requester.id %}">
                        {{ request.requester.username }}
                    </a>
                </td>
                <td>{{ request.rent_start_time }}</td>
                <td>{{ request.rent_end_time }}</td>
                <td>{{ request.get_price }}</td>
                <td>
                    <label for="yes{{ forloop.counter }}">Yes</label>
                    <input type="radio" id="yes{{ forloop.counter }}" name="{{ request.id }}" value="yes">
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <label for="no{{ forloop.counter }}">No</label>
                    <input type="radio" id="no{{ forloop.counter }}" name="{{ request.id }}" value="no">
                </td>
            </tr>
         {% endfor %}
        </tbody>
        </table>
        <input value="Confirm" type="submit" class="btn btn-info">
        </form>
    {% else %}
        <div class="alert alert-danger"><strong>No Requests.</strong></div>
    {% endif %}
</div>
{% endblock %}

car_rental/templates/car_rental/staff_detail.html
{% extends 'car_rental/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block title %} Staff Details {% endblock %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'car_rental/stylesheets/car_detail.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'car_rental/stylesheets/request_list.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h1>Staff number {{ staff.id }}</h1>

        <table class="table table-striped table-hover info-table">
            <tr>
                <td>Username</td>
                <td>{{ staff.user.username }}</td>
            </tr>
            <tr>
                <td>Type</td>
                <td>{% if staff.is_senior %} Senior {% else %} Normal {% endif %}</td>
            </tr>
            <tr>
                <td>User ID</td>
                <td>{{ staff.user.id }}</td>
            </tr>
        </table>

{% if perms.car_rental.can_access_staff %}
        <a class="btn btn-info" href="{% url 'car_rental:delete_staff' staff.user.id %}" role="button" style="width:19%">Remove This Staff</a>
        <a class="btn btn-info" href="{% url 'car_rental:staff_perms' staff.id %}" role="button" style="width:19%">Edit Permissions</a>
{% endif %}

{% if staff.rentrequest_set.all %}
        <h1>Answered Requests</h1>

<table class="table table-striped table-hover" style="margin-top: 20px">
        <thead>
        <tr>
            <td>#</td>
            <td>Model</td>
            <td>Start Time</td>
            <td>End Time</td>
            <td>Price</td>
            <td>Result</td>
        </tr>
        </thead>
        <tbody>
        {% for request in staff.rentrequest_set.all %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    {% if request.car %}
                    <a href="{% url 'car_rental:car' request.car.id %}">{{ request.car.car_type }}</a>
                    {% else %}
                    Deleted Car
                    {% endif %}
                </td>
                <td>{{ request.rent_start_time }}</td>
                <td>{{ request.rent_end_time }}</td>
                <td>{{ request.get_price }}</td>
                {% if request.is_accepted %}
                    <td style="color: darkgreen">Accepted</td>
                {% else %}
                    <td style="color: darkred">Rejected</td>
                {% endif %}
            </tr>
         {% endfor %}
        </tbody>
        </table>
{% else %}
       <div class="alert alert-danger" style="margin-top: 20px"><strong>This staff has answered no requests till now.</strong></div>
{% endif %}
</div>
{% endblock %}